###############
## AUTOSTART ##
###############

## Streamdeck
# exec-once = flatpak run com.core447.StreamController -b
exec-once = streamcontroller -b

## Themeing
exec-once = killall -q swww;sleep .5 && swww init
exec-once = killall -q waybar;sleep .5 && waybar
exec-once = killall -q swaync;sleep .5 && swaync


##########
## Main ##
##########

monitor = DP-1, highres@highrr, 0x0, 1
monitor = DP-2, highres@highrr, -2560x-40, 1

## Vnc testing
monitor = VNC-1, 1920x1080@60, 0x0, 1, mirror, DP-1

input {
  kb_layout = us
  # kb_options = grp:alt_shift_toggle
  follow_mouse = 1
  numlock_by_default=true
  touchpad {
    natural_scroll = true
    disable_while_typing = true
    scroll_factor = 0.8
  }
  sensitivity = 0 ## -1.0 - 1.0, 0 means no modification.
  accel_profile = flat
}

gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 3
}

## hyprsplit
plugin {
    hyprsplit {
        num_workspaces = 6
    }
}


##############
## Keybinds ##
##############

## Split monitor plugin
## Switch workspaces with mod + [0-5]
bind = $mod, 1, split:workspace, 1
bind = $mod, 2, split:workspace, 2
bind = $mod, 3, split:workspace, 3
bind = $mod, 4, split:workspace, 4
bind = $mod, 5, split:workspace, 5

## Switch workspaces with mod + mouse side scrol
bindp = $mod, mouse:276, split:workspace, +1
bindp = $mod, mouse:275, split:workspace, -1

## Move active window to a workspace with mod + SHIFT + [0-5]
bind = $mod SHIFT, 1, split:movetoworkspace, 1
bind = $mod SHIFT, 2, split:movetoworkspace, 2
bind = $mod SHIFT, 3, split:movetoworkspace, 3
bind = $mod SHIFT, 4, split:movetoworkspace, 4
bind = $mod SHIFT, 5, split:movetoworkspace, 5

## Move active window to a workspace
bind = $mod SHIFT, mouse:276, split:movetoworkspace, +1
bind = $mod SHIFT, mouse:275, split:movetoworkspace, -1

## Move active workspace to other monitor
bind = $mod, mouse_right, split:swapactiveworkspaces, current +1
bind = $mod, mouse_left, split:swapactiveworkspaces, current -1

## spcial Workspace Discord
bind = $mod, D, togglespecialworkspace, discord
bind = $mod SHIFT, D, split:movetoworkspace, special:discord

## special workspace Sound for spotify, qpw, ect
bind = $mod, S, togglespecialworkspace, sound
bind = $mod SHIFT, S, split:movetoworkspace, special:sound

## special workspace for Steam
bind = $mod, G, togglespecialworkspace, steam
bind = $mod SHIFT, G, split:movetoworkspace, special:steam

bind = $mod, A, togglespecialworkspace, A
bind = $mod SHIFT, A, split:movetoworkspace, special:A

