##########
## Main ##
##########

monitor = eDP-1, highres@highrr, 0x0, 1.175
monitor = , highres@highrr, 0x1504, auto

xwayland {
force_zero_scaling = true
} 

input {
  kb_layout = us
  # kb_options = grp:alt_shift_toggle
  follow_mouse = 1
  numlock_by_default=true
  touchpad {
    natural_scroll = true
    disable_while_typing = true
    scroll_factor = 0.8
  }
  sensitivity = 0.1 ## -1.0 - 1.0, 0 means no modification.
  accel_profile = flat
}

# gestures {
#   workspace_swipe = true
#   workspace_swipe_fingers = 3
# }


##############
## Keybinds ##
##############

## Dissable trackpad
# bind = $mod SHIFT, T, ## DISSABLE TRACKPAD

## Switch workspaces with mod + [0-9] ## Old without plugin
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

## Switch workspaces with mod + mouse side scrol
bindp = $mod, mouse:276, workspace, +1
bindp = $mod, mouse:275, workspace, -1

## Move active window to a workspace with mod + SHIFT + [0-9]
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

### Move active window to a workspace
#bind = $mod SHIFT, mouse:276, movetoworkspace, +1
#bind = $mod SHIFT, mouse:275, movetoworkspace, -1

## spcial Workspace Discord
bind = $mod, D, togglespecialworkspace, discord
bind = $mod SHIFT, D, movetoworkspace, special:discord

## special workspace Sound for spotify, qpw, ect
bind = $mod, S, togglespecialworkspace, sound
bind = $mod SHIFT, S, movetoworkspace, special:sound

## special workspace for Steam
bind = $mod, G, togglespecialworkspace, steam
bind = $mod SHIFT, G, movetoworkspace, special:steam

bind = $mod, A, togglespecialworkspace, A
bind = $mod SHIFT, A, movetoworkspace, special:A
