##########
## Main ##
##########

monitor = , highres@highrr, 0x0, 1.175
# debug:disable_scale_check=true

xwayland {
force_zero_scaling = true
} 

input {
  kb_layout = us
  # kb_options = grp:alt_shift_toggle
  follow_mouse = 1
  numlock_by_default=true
  touchpad {
    natural_scroll = true
    disable_while_typing = true
    scroll_factor = 0.8
  }
  sensitivity = 0 ## -1.0 - 1.0, 0 means no modification.
  accel_profile = flat
}

gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 3
}