##########
## Main ##
##########

# monitor = eDP-1, highres@highrr, 0x0, 1.175
# monitor = , highres@highrr, 0x1504, auto
source = ./monitors.conf

xwayland {
force_zero_scaling = true
}

## Discord
# exec-once = [workspace special:discord silent] killall -q equibop;sleep .5 && equibop

input {
  kb_layout = us
  # kb_options = grp:alt_shift_toggle
  follow_mouse = 1
  numlock_by_default=true
  touchpad {
    natural_scroll = true
    disable_while_typing = true
    scroll_factor = 0.8
  }
  sensitivity = 0.1 ## -1.0 - 1.0, 0 means no modification.
  accel_profile = flat
}

# gesture = 3, horizontal, workspace
